CREATE TABLE SUSTAINABLELIVINGCategories (
SUSTAINABLELIVINGCategoryID       INT(11)        NOT NULL,
SUSTAINABLELIVINGCategoryCode     VARCHAR(255)   NOT NULL   UNIQUE,
SUSTAINABLELIVINGCategoryName     VARCHAR(255)   NOT NULL,
DateCreated              DATETIME       NOT NULL,
Size                   INT(11)    NOT NULL,
PRIMARY KEY ( SUSTAINABLELIVINGCategoryID )
);

SELECT * FROM SUSTAINABLELIVINGCategories;

INSERT INTO SUSTAINABLELIVINGCategories
(SUSTAINABLELIVINGCategoryID, SUSTAINABLELIVINGCategoryCode, SUSTAINABLELIVINGCategoryName, DateCreated, Size)
VALUES
(100, 'RWB', 'Reusable Water Bottle', NOW(),7 );
INSERT INTO SUSTAINABLELIVINGCategories
(SUSTAINABLELIVINGCategoryID, SUSTAINABLELIVINGCategoryCode, SUSTAINABLELIVINGCategoryName, DateCreated, Size)
VALUES
(200, 'BTS', 'Bamboo Toothbrush Set', NOW(),5);
INSERT INTO SUSTAINABLELIVINGCategories
(SUSTAINABLELIVINGCategoryID, SUSTAINABLELIVINGCategoryCode, SUSTAINABLELIVINGCategoryName, DateCreated, Size)
VALUES
(300, 'SPC', 'Solar-powered Charger', NOW(),4);
INSERT INTO SUSTAINABLELIVINGCategories
(SUSTAINABLELIVINGCategoryID, SUSTAINABLELIVINGCategoryCode, SUSTAINABLELIVINGCategoryName, DateCreated, Size)
VALUES
(400, 'ESB', 'Eco-friendly Shopping Bag', NOW(),11);
INSERT INTO SUSTAINABLELIVINGCategories
(SUSTAINABLELIVINGCategoryID, SUSTAINABLELIVINGCategoryCode, SUSTAINABLELIVINGCategoryName, DateCreated, Size)
VALUES
(500, 'LED', 'LED Bulbs', NOW(),4);




